### PR TITLE
References were formatted incorrectly on Windows

### LINKED ISSUE #446: Windows tests failing with OCI paths
There are two components to this bug:

1. Windows tests pipelines are still showing green even when there are failures. This likely has something to do with my lack of Powershell skills
2. There are currently failures with the OCI crate:

```
failures:
    store::oci::file::test::file_module_store_always_pulls_if_tag_and_policy_omitted
    store::oci::file::test::file_module_store_always_pulls_if_tag_latest_and_policy_omitted
    store::oci::file::test::file_module_store_can_pull_if_policy_always
    store::oci::file::test::file_module_store_can_pull_if_policy_if_not_present
    store::oci::file::test::file_module_store_can_pull_if_tag_given_but_policy_omitted
    store::oci::file::test::file_module_store_can_reuse_cached_if_policy_never
    store::oci::file::test::file_module_store_copes_with_no_tag
    store::oci::file::test::file_module_store_gets_updates_if_policy_always
    store::oci::file::test::file_module_store_ignores_updates_if_policy_if_not_present

test result: FAILED. 25 passed; 9 failed; 0 ignored; 0 measured; 0 filtered out
```

This is causing problems with other parts of the code as well: 
```
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"docker.io/library/hello-world:latest"`,
 right: `"docker.io\\library/hello-world:latest"`', src\reference.rs:8:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

You can see an example run and output [here](https://github.com/deislabs/krustlet/runs/1316193432?check_suite_focus=true#step:4:1277)

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #446

### CODE REVIEW

File: crates/oci-distribution/src/reference.rs [hunk 1]
```diff
@@ -90,10 +89,7 @@ impl Reference {
 
     /// full_name returns the full repository name and path.
     fn full_name(&self) -> String {
-        let mut path = PathBuf::new();
-        path.push(self.registry());
-        path.push(self.repository());
-        path.to_str().unwrap_or("").to_owned()
+        format!("{}/{}", self.registry(), self.repository())
```
Comment (bacongobbler) [inline crates/oci-distribution/src/reference.rs:92]: It is possible that `self.registry()` may return an empty string, which will result in a string like `/foo`. The previous code caught this scenario because an empty string would return `foo`.

One way to fix might be to check if `self.registry()` returns an empty string, and only join the two together if it exists.

It might be worth writing a unit test just to make sure I'm not totally wrong that the old code did indeed work as I described...

Comment (itowlson) [reply crates/oci-distribution/src/reference.rs:92]: Good catch - thanks!

Comment (itowlson) [reply crates/oci-distribution/src/reference.rs]: Fixed and test added - please take another look when convenient

**Review by bacongobbler — APPROVED** [review]
