### PR TITLE
port docker/distribution's regular expressions

### LINKED ISSUE #397: bug: images without a slash in the name should be accepted
```
[2020-09-23T21:44:17Z ERROR wasi_provider::states::registered] Failed to parse reference string 'nginx'. Expected at least one slash (/)
```

Names like `nginx` are valid image references.

### PR DESCRIPTION
**Pull request by bacongobbler**
This allows us to properly parse reference types. Test cases from docker/distribution are included as well to demonstrate what reference types are valid/invalid.

This supersedes #406.
closes #397

### CODE REVIEW

File: crates/oci-distribution/src/regexp.rs [hunk 1]
```diff
@@ -0,0 +1,16 @@
+use regex::{Regex, RegexBuilder};
+
+/// REFERENCE_REGEXP is the full supported format of a reference. The regexp
+// is anchored and has capturing groups for name, tag, and digest components.
+pub const REFERENCE_REGEXP: &str = r"^((?:(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9])(?:(?:\.(?:[a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]))+)?(?::[0-9]+)?/)?[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?(?:(?:/[a-z0-9]+(?:(?:(?:[._]|__|[-]*)[a-z0-9]+)+)?)+)?)(?::([\w][\w.-]{0,127}))?(?:@([A-Za-z][A-Za-z0-9]*(?:[-_+.][A-Za-z][A-Za-z0-9]*)*[:][[:xdigit:]]{32,}))?$";
```
Comment (radu-matei) [inline crates/oci-distribution/src/regexp.rs:5]: I assume this is the regular expression used by upstream tools (`containerd`?).

Could you link the original file where this is defined?

Comment (bacongobbler) [reply crates/oci-distribution/src/regexp.rs:5]: Sure!

https://github.com/docker/distribution/blob/2800ab02245e2eafc10e338939511dd1aeb5e135/reference/regexp.go#L58-L70

**Review by radu-matei — APPROVED** [review]
