### PR TITLE
Insecure registries

### LINKED ISSUE #356: handling image from insecure registry
I set up a local registry with [kind](https://kind.sigs.k8s.io/docs/user/local-registry/). I pushed web assembly image via wasm-to-oci, but wasn't able to deploy the workload via kubectl. kubectl describe pod POD_NAME points to error message that krustlet is using https instead of http. 

`Message:      error sending request for url (https://localhost:5000/v2/): error trying to connect: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:332:`

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #356.

I'm not quite sure how to test this.  I've tested the config and the URL building, but can't see how to verify that it works end to end.  @amar123deep, would you be able to pull this PR and give it a test in your Kind environment please?

### CODE REVIEW

File: crates/kubelet/src/config.rs [hunk 1]
```diff
@@ -633,6 +657,9 @@ mod test {
         assert_eq!(config.allow_local_modules, true);
         assert_eq!(config.node_labels.len(), 2);
         assert_eq!(config.node_labels.get("label1"), Some(&("val1".to_owned())));
+        assert_eq!(config.insecure_registries.clone().unwrap().len(), 2);
+        assert_eq!(&config.insecure_registries.clone().unwrap()[0], "local");
```
Comment (thomastaylor312) [inline crates/kubelet/src/config.rs:661]: Nit: Because this is the end of the test, you could just do something like this to make things a bit less gnarly:

```rust
let insecure_registries = config.insecure_registries.expect("registries")
...do assertions here
```

File: crates/kubelet/src/lib.rs [hunk 2]
```diff
@@ -55,6 +55,7 @@ pub(crate) mod kubeconfig;
 pub(crate) mod webserver;
 
 pub mod config;
+pub mod config_interpreter;
```
Comment (thomastaylor312) [inline crates/kubelet/src/lib.rs:58]: Just to clarify: This is `pub` because of the trait implementation in `config_interpreter`?

File: crates/oci-distribution/src/client.rs [hunk 3]
```diff
@@ -47,6 +47,12 @@ pub struct Client {
     client: reqwest::Client,
 }
 
+/// A source that can provide a `ClientConfig`.
```
Comment (thomastaylor312) [inline crates/oci-distribution/src/client.rs:50]: Nit: It might be good to expand the documentation here a bit to say something like "This is useful when writing your own configuration for an application as it can implement this trait to provide a `ClientConfig`"

File: crates/oci-distribution/src/reference.rs [hunk 4]
```diff
@@ -52,21 +52,21 @@ impl Reference {
     }
 
     /// Convert a Reference to a v2 manifest URL.
-    pub fn to_v2_manifest_url(&self, protocol: &str) -> String {
+    pub fn to_v2_manifest_url(&self, protocol: &crate::client::ClientProtocol) -> String {
```
Comment (thomastaylor312) [inline crates/oci-distribution/src/reference.rs:55]: I really like having this be an enum over a bare `&str`

File: crates/kubelet/src/lib.rs (hunk 2 above)
Comment (itowlson) [reply crates/kubelet/src/lib.rs:58]: I thought it needed to be but it looks like having it private still works!  Fixed!  Thanks!

File: crates/kubelet/src/config.rs (hunk 1 above)
Comment (itowlson) [reply crates/kubelet/src/config.rs:661]: Might skip that because it could become a source of unrelated changes if a subsequent PR added test lines after these ones... this whole area could do with a bit more granularity though, to avoid this sort of gnarl!

**Comment by bacongobbler** [comment]
needs a rebase, but LGTM!

**Comment by itowlson** [comment]
Rebase was a bit fiddly, might not hurt to take another look...
